services:
  php-apache:
    build:
      context: .  # This is the root context where docker-compose.yml is located
      dockerfile: .docker/Dockerfile  # Path to your Dockerfile
    container_name: blog_php
    volumes:
      - ./:/var/www/html:rw
    ports:
      - "8080:80"
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
