services:
  php-apache:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: blog_php
    volumes:
      - ./:/var/www/html:rw
    ports:
      - "8080:80"
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
